### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/harperdb-connect#3]
Write API spec documentation

Use https://getpino.io/#/docs/API as inspiration

**Comment by Trancever** [comment]
I did a little research and found out that we should use gitbook to generate such documentation format. I can take this task and try to set up the build process, is it ok?  As a reference i'll use redux docs, it's also using gitbook.

**Comment by Ethan-Arrowood** [comment]
Yeah for sure!

**Comment by Trancever** [comment]
#11
