### ISSUE TITLE
Add expected assertions to unit tests

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/harperdb-connect#7]
https://facebook.github.io/jest/docs/en/expect.html#expectassertionsnumber

**Comment by Trancever** [comment]
Hello Ethan, i would like to work on it. I just have a question about implementation. Should I specify expected assertions in both synchronous and asynchronous tests or only in async ?

**Comment by Ethan-Arrowood** [comment]
Awesome! Start with asynchronous only for now. I’ll do a little more reading on what to do for synchronous only tests.

**Comment by Trancever** [comment]
Created pull request - #9 . Also found out a little mistake probably, more details in PR description.
